routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'MainController@index');
    Route::resource('group','GroupController');
    Route::prefix('/user/')->group(function () {
        Route::resource('list','UserController');
        Route::get('ugroup/{id}','UserController@getUgroup');
        Route::post('ugroup/update','UserController@ugroupUpdate');
    });
    Route::prefix('/ugroup/')->group(function () {
        Route::resource('list','UgroupController');
        Route::get('user/{id}','UgroupController@getUser');
        Route::post('user/update','UgroupController@userUpdate');
        Route::get('service/{id}','UgroupController@getService');
        Route::post('service/update','UgroupController@serviceUpdate');
    });

    Route::resource('client','ClientController');
    Route::get('log','LogController@index');
    Route::get('service_log','LogController@ServiceLog');

    Route::get('service', 'ServiceController@index');
    Route::post('service', 'ServiceController@index');
    Route::get('service/input', 'ServiceController@serviceInput');
    Route::post('service/input', 'ServiceController@serviceInput');
    Route::get('service/output', 'ServiceController@serviceCall');
    Route::get('service/client/lookup', 'ServiceController@lookupClient');
    Route::post('service/client/lookup', 'ServiceController@lookupClient');
    Route::get('get-pdf', 'ServiceController@makePdf');
});

Auth::routes();

Route::group(['middleware' => ['ApiAuth']], function () {
    Route::get('api/log', 'ApiController@log');
    Route::post('api/xyp/proxy', 'ApiController@anket');
});

Route::get('wrong', function () {
    return view('wrong');
});

Route::get('user/bootstrap', 'UserController@bootstrapUser');

resources/views/home.blade.php
@extends('layouts.master')
@section('content')
<div class="toggler">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor" style="padding: 0.375rem 0.75rem;">Нүүр хуудас</h4>
        </div>

    </div>

    <div class="card border-info">
        <div class="card-header bg-info">
            <h4 class="m-b-0 text-white">Үйлчилгээ сонгох</h4>
        </div>
        <div class="card-body">
            <div class="row">
                @foreach($groups as $group)
                    <div class="col-lg-3 col-md-3">
                        <div class="card text-white bg-info">
                            <div class="card-body">
                                <h4 class="m-b-0 text-white">{{ $group->title }} <a class="get-code" data-toggle="collapse" href="#tt-{{$group->id}}" aria-expanded="true"><i class="icon-info" title="Дэлгэрэнгүй" data-toggle="tooltip"></i></a></h4>
                                <div class="collapse m-t-15" id="tt-{{$group->id}}" aria-expanded="true">
                                    <ul class="list-group">
                                    @foreach($group->services as $service)
                                            <li class="list-group-item" style="color:#2f7396;"> {{ $service->title }}</li>
                                    @endforeach
                                    </ul>
                                </div>
                            </div>
                            <div class="card-footer text-center" >
                                <a href="{{ url('select') }}" type="button" class="btn btn-rounded" style="background-color: #fff; color: #2f7396;"> сонгох</a>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>



    <div class="card border-info">
        <div class="card-header bg-info">
            <h4 class="m-b-0 text-white">Үйлчилгээ үүсгэх</h4>
        </div>
        <div class="card-body">
            <form class="form-material" action="{{ route('group.store') }}" method="post">
                {{ csrf_field() }}
                <div class="input-group">
                        @foreach($webservices as $webservice)
                            <div class="col-lg-3 col-md-3 m-b-20">
                                <input  name="webs[]" type="checkbox" value="{{$webservice->id}}" class="check form-group m-l-15" id="minimal-checkbox-{{ $loop->index+1 }}" data-checkbox="icheckbox_square-red">
                                <label class="icheck-label" for="minimal-checkbox-{{ $loop->index+1 }}">{{ $webservice->title }}</label>

                            </div>
                        @endforeach
                </div>
                <hr>
                <div class="row footer_btn">
                    <button class="btn btn-rounded btn-info m-l-15" type="submit"><i class="fa fa-plus-circle"></i> үүсгэх</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@push('styles')
    <link href="/assets/node_modules/icheck/skins/all.css" rel="stylesheet">
    <link href="dist/css/pages/form-icheck.css" rel="stylesheet">
    <link href="dist/css/pages/stylish-tooltip.css" rel="stylesheet">

    <style>
        .footer_btn{
            float: right;
        }
        .icheckbox_square-red{
            vertical-align: top;
        }
        .icheck-label{
            width: calc(100% - 30px);
        }
    </style>
@endpush
@push('scripts')
    <script>
        $(window).on("load", function () {
            $("body").trigger("resize");
            $("body").addClass("mini-sidebar");
            $('.navbar-brand span').hide();
        });
    </script>
    <script src="/assets/node_modules/icheck/icheck.min.js"></script>
    <script src="/assets/node_modules/icheck/icheck.init.js"></script>
@endpush

resources/views/test.blade.php
/**
 * Created by PhpStorm.
 * User: ganbayar
 * Date: 9/2/18
 * Time: 5:17 PM
 */
@extends('layouts.master')
@section('content')
{{ var_dump(unserialize($data)->response) }}
 @endsection

resources/views/wrong.blade.php
access token invalid